// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace summertermminiproject
{
	public partial class NewInventory : NSViewController
	{
		public NewInventory (IntPtr handle) : base (handle)
		{
		}
	}
}
